// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfzlDjRWMKjGZ2gldb0twqyTGflHXasXc',
    appId: '1:445140589048:web:9261233bb28aad1c839e0d',
    messagingSenderId: '445140589048',
    projectId: 'dbeprojectadse2',
    authDomain: 'dbeprojectadse2.firebaseapp.com',
    storageBucket: 'dbeprojectadse2.appspot.com',
    measurementId: 'G-L01XGLEL9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDiV7WHzAgnqxxZuBOEpCk5c5bwLuBw0',
    appId: '1:445140589048:android:507d647735499661839e0d',
    messagingSenderId: '445140589048',
    projectId: 'dbeprojectadse2',
    storageBucket: 'dbeprojectadse2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4O28DtrW5IoihK7JixJr4qxVwKKXAmTM',
    appId: '1:445140589048:ios:95c4d71abd0ef2c4839e0d',
    messagingSenderId: '445140589048',
    projectId: 'dbeprojectadse2',
    storageBucket: 'dbeprojectadse2.appspot.com',
    iosBundleId: 'com.example.epSem4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4O28DtrW5IoihK7JixJr4qxVwKKXAmTM',
    appId: '1:445140589048:ios:95c4d71abd0ef2c4839e0d',
    messagingSenderId: '445140589048',
    projectId: 'dbeprojectadse2',
    storageBucket: 'dbeprojectadse2.appspot.com',
    iosBundleId: 'com.example.epSem4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfzlDjRWMKjGZ2gldb0twqyTGflHXasXc',
    appId: '1:445140589048:web:104d52e60ab76c3b839e0d',
    messagingSenderId: '445140589048',
    projectId: 'dbeprojectadse2',
    authDomain: 'dbeprojectadse2.firebaseapp.com',
    storageBucket: 'dbeprojectadse2.appspot.com',
    measurementId: 'G-KL4FS03VQ1',
  );
}
